### ISSUE TITLE
Difference in accuracy question

### ISSUE THREAD

**Issue by adam-hartshorne** [hr0nix/optax-adan#2]
It appears somebody else has written a pull request for an implementation of the Adan optimizer for Optax. I pointed out that your implementation already existed and it is claimed that in testing that your version is "3 order of magnitude larger error". 

https://github.com/deepmind/optax/issues/401

Is there potentially a bug in your code?

**Comment by hr0nix** [comment]
Thanks for pointing that out! I'll take a look

**Comment by hr0nix** [comment]
Took a look at it, the difference comes from where epsilon is placed: https://github.com/deepmind/optax/issues/401#issuecomment-1250333715

Not sure if that's important, but I'll push this change so that this implementation is more similar to reference.
